// ─── Hindu Ceremony Data ───────────────────────────────────────────
// Focused on Hindu traditions first. Other traditions can be added later.

export interface CeremonyDetail {
  name: string;
  sanskrit?: string;
  slug: string;
  duration: string;
  timing: string;
  description: string;
  significance: string;
  keySteps: string[];
  items: string[];
  familyRole: string;
  modernNote?: string;
}

export interface SubSection {
  label: string;
  ceremonies: CeremonyDetail[];
}

export interface Category {
  id: string;
  label: string;
  icon: string;
  intro: string;
  subSections: SubSection[];
}

export const CATEGORIES: Category[] = [
  // ───────────────────── WEDDING ─────────────────────
  {
    id: "wedding",
    label: "Wedding",
    icon: "ring",
    intro: "A Hindu wedding is not a single event but a series of sacred rituals spanning days. Each ceremony strengthens the bond between two families and invokes divine blessings for the couple's journey together.",
    subSections: [
      {
        label: "Pre-Wedding",
        ceremonies: [
          {
            name: "Roka",
            sanskrit: "Roka / Tilak",
            slug: "roka",
            duration: "1 hour",
            timing: "Weeks or months before wedding",
            description: "The formal agreement between families that a marriage will take place. The bride's family visits the groom and applies tilak on his forehead, presenting sweets and gifts.",
            significance: "Marks the official acceptance from both families. After Roka, the families publicly acknowledge the match and begin wedding preparations.",
            keySteps: [
              "Groom's family welcomes bride's family",
              "Tilak applied on groom's forehead with kumkum and rice",
              "Exchange of sweets, dry fruits, and gifts",
              "Shagun (auspicious monetary gift) presented",
              "Date discussions for Sagai begin",
            ],
            items: ["Kumkum", "Rice", "Coconut", "Sweets", "Dry fruits", "Shagun envelope"],
            familyRole: "Bride's father or eldest male applies tilak. Mothers exchange gifts.",
            modernNote: "Often combined with Sagai (engagement) in a single event for families in the diaspora.",
          },
          {
            name: "Sagai",
            sanskrit: "Sagai / Mangni",
            slug: "sagai",
            duration: "2 to 3 hours",
            timing: "Weeks or months before wedding",
            description: "The formal engagement ceremony where rings are exchanged and the couple is officially betrothed. A Mahraj may perform a brief Ganesh pooja to bless the occasion.",
            significance: "Solidifies the bond between families with the exchange of rings and blessings. It is the first ceremony where both families celebrate together publicly.",
            keySteps: [
              "Ganesh Sthapana and brief prayer",
              "Exchange of rings between bride and groom",
              "Both families exchange gifts and sweets",
              "Elders bless the couple",
              "Celebration with music and food",
            ],
            items: ["Rings", "Ganesh murti", "Flowers", "Sweets", "Gift trays", "Coconut"],
            familyRole: "Parents and grandparents from both sides place their blessings. Siblings often help with gift presentation.",
          },
          {
            name: "Ganesh Sthapana",
            sanskrit: "Ganesh Sthapana",
            slug: "ganesh-sthapana-wedding",
            duration: "45 minutes",
            timing: "Start of wedding events, or morning of the wedding day",
            description: "Invocation of Lord Ganesh, the remover of obstacles, to bless all upcoming wedding ceremonies. A small murti or image is installed and worshipped.",
            significance: "No Hindu ceremony begins without first honoring Ganesh. This sets the spiritual foundation for every ritual that follows.",
            keySteps: [
              "Purification of the pooja space",
              "Installation of Ganesh murti with turmeric and kumkum",
              "Chanting of Ganesh mantras and aarti",
              "Offering of modak, durva grass, and flowers",
              "Prayer for removal of obstacles from all wedding events",
            ],
            items: ["Ganesh murti or image", "Turmeric", "Kumkum", "Durva grass", "Modak or laddoo", "Flowers", "Diya and incense"],
            familyRole: "Typically performed by the bride's family at their home. Both parents participate in the aarti.",
          },
          {
            name: "Mehndi",
            slug: "mehndi",
            duration: "3 to 5 hours",
            timing: "1 to 2 days before the wedding",
            description: "Intricate henna designs are applied to the bride's hands and feet. Traditionally, the groom's name or initials are hidden within the design for him to find on the wedding night.",
            significance: "Mehndi symbolizes love, beauty, and the bond between the couple. The darker the mehndi color, the stronger the love is said to be. It also has cooling properties, helping the bride stay calm.",
            keySteps: [
              "Professional mehndi artist applies bridal designs (hands, arms, feet)",
              "Bridesmaids and female family members also get mehndi",
              "Singing of traditional mehndi songs",
              "Groom's initials hidden in the design",
              "Bride rests while mehndi dries and darkens",
            ],
            items: ["Mehndi cones", "Lemon-sugar solution (to darken)", "Essential oils", "Cushions for the bride"],
            familyRole: "Women from both families celebrate together. Mother-in-law often applies the first dot of mehndi.",
            modernNote: "Many families host a combined Mehndi and Sangeet party for convenience.",
          },
          {
            name: "Haldi",
            sanskrit: "Haldi / Pithi",
            slug: "haldi",
            duration: "1 to 2 hours",
            timing: "Morning of the wedding day or day before",
            description: "A paste of turmeric, sandalwood, and rosewater is applied to the bride and groom (separately, at their own homes) by close family members. It is a joyful, often playful ceremony.",
            significance: "Turmeric is believed to purify the body and give the skin a golden glow. It also has antiseptic properties. The ceremony blesses the couple with health and beauty for their new life.",
            keySteps: [
              "Bride/groom seated on a low stool or paat",
              "Haldi paste prepared with turmeric, sandalwood, and rosewater",
              "Close family members apply paste to face, arms, and feet",
              "Five married women (suhagans) apply haldi for good luck",
              "Playful celebration follows with music and dance",
            ],
            items: ["Turmeric powder", "Sandalwood paste", "Rosewater", "Mango leaves", "Low wooden stool (paat)", "Old clothes (haldi stains!)"],
            familyRole: "Maternal uncle and aunt typically start. All close relatives take turns. Often a loud, joyful, messy affair.",
          },
          {
            name: "Sangeet",
            slug: "sangeet",
            duration: "3 to 5 hours (evening event)",
            timing: "1 to 2 nights before the wedding",
            description: "A celebratory musical evening where both families perform choreographed dances, sing traditional songs, and celebrate the upcoming union. Part performance, part party.",
            significance: "Originally a gathering where women from the bride's family sang folk songs about marriage. Today it is the most festive pre-wedding event, bringing both families together through music and dance.",
            keySteps: [
              "Welcome and opening performances",
              "Bride's side and groom's side perform choreographed dances",
              "Couple's joint performance (if desired)",
              "Traditional folk songs and bollywood medleys",
              "Dinner and open dance floor",
            ],
            items: ["Sound system and lighting", "Stage or dance floor", "Coordinated outfits for performers"],
            familyRole: "All family members and friends participate. Often organized by siblings and cousins.",
            modernNote: "Not a religious ceremony, so no Mahraj is needed. But it is a core part of the modern Hindu wedding experience.",
          },
        ],
      },
      {
        label: "Wedding Day",
        ceremonies: [
          {
            name: "Baraat",
            slug: "baraat",
            duration: "30 to 60 minutes",
            timing: "Arrival at the wedding venue",
            description: "The groom's grand procession to the wedding venue. Traditionally on a horse or in a decorated car, accompanied by a band, dancing family, and friends.",
            significance: "Symbolizes the groom's journey to claim his bride. The energy and joy of the baraat set the tone for the entire wedding celebration.",
            keySteps: [
              "Groom mounts decorated horse or enters vehicle",
              "Band leads the procession with dhol and shehnai",
              "Family and friends dance alongside",
              "Fireworks or sparklers (venue permitting)",
              "Procession arrives at the wedding venue entrance",
            ],
            items: ["Decorated horse or vehicle", "Sehra (face veil for groom)", "Dhol/band", "Flower garlands", "Sparklers"],
            familyRole: "Groom's mother performs aarti before departure. Groom's male relatives and friends lead the dancing.",
          },
          {
            name: "Milni",
            slug: "milni",
            duration: "15 to 20 minutes",
            timing: "At the venue entrance, after baraat arrives",
            description: "The formal meeting of the two families at the entrance of the wedding venue. Corresponding relatives (father meets father, uncle meets uncle) exchange garlands and embrace.",
            significance: "Symbolizes the union of two families, not just two individuals. Each pair of relatives acknowledges their new bond.",
            keySteps: [
              "Bride's family welcomes groom's procession",
              "Bride's mother performs aarti of the groom",
              "Corresponding family members exchange garlands",
              "Playful 'lifting' competition (who can lift whom higher)",
              "Families enter the venue together",
            ],
            items: ["Garlands for each pair", "Aarti thali", "Tilak set"],
            familyRole: "Both sets of parents, uncles, and grandfathers participate in the matching garland exchange.",
          },
          {
            name: "Jaimala",
            sanskrit: "Jaimala / Varmala",
            slug: "jaimala",
            duration: "10 to 15 minutes",
            timing: "After Milni, at the mandap or stage",
            description: "The bride and groom exchange heavy floral garlands, symbolizing their voluntary acceptance of each other. Friends and family often playfully lift each to make it difficult for the other to place their garland.",
            significance: "Unlike an arranged introduction, Jaimala represents the couple's free will to accept each other. It is one of the most photographed moments of the wedding.",
            keySteps: [
              "Bride and groom face each other on stage",
              "Groom places garland around bride's neck",
              "Bride places garland around groom's neck",
              "Friends may lift the groom to make it harder for the bride",
              "Cheering and celebration from guests",
            ],
            items: ["Two heavy floral garlands (rose, marigold, or jasmine)", "Stage or elevated platform"],
            familyRole: "Friends and siblings create playful competition. Guests cheer.",
          },
          {
            name: "Kanyadaan",
            sanskrit: "Kanyadaan",
            slug: "kanyadaan",
            duration: "20 to 30 minutes",
            timing: "At the mandap, before the pheras",
            description: "The bride's father places her hand in the groom's, formally giving his daughter in marriage. Water is poured over their joined hands. It is considered the most sacred gift a father can give.",
            significance: "Kanyadaan is regarded as the highest form of daan (charitable giving) in Hindu scripture. The father entrusts his daughter to the groom's care, and the groom vows to honor her.",
            keySteps: [
              "Bride's father leads her to the mandap",
              "Mantras invoking Brahma, Vishnu, and the ancestors",
              "Father places bride's right hand in groom's right hand",
              "Holy water poured over their joined hands",
              "Groom vows to treat the bride with respect, love, and equality",
              "Bride's mother pours water, completing the offering",
            ],
            items: ["Water vessel (lota)", "Flowers", "Rice", "Mango leaves"],
            familyRole: "Father and mother of the bride are central. Maternal uncle often supports the bride's father.",
          },
          {
            name: "Vivah",
            sanskrit: "Vivah / Pheras",
            slug: "vivah",
            duration: "2 to 3 hours",
            timing: "Main ceremony, muhurat-based (often late evening)",
            description: "The heart of the Hindu wedding. The couple takes seven rounds (pheras) around the sacred fire (Agni), each round accompanied by a specific vow. The fire serves as the divine witness to their promises.",
            significance: "The seven vows cover every aspect of married life: nourishment, strength, prosperity, happiness, progeny, health, and lifelong friendship. The fire god Agni is the eternal witness, making the bond sacred and unbreakable.",
            keySteps: [
              "Sacred fire (havan) lit in the mandap",
              "Groom ties bride's pallu to his scarf (gathbandhan)",
              "First three pheras led by the bride (she walks in front)",
              "Last four pheras led by the groom",
              "Each round accompanied by a specific Vedic vow",
              "Offerings of puffed rice and ghee into the fire",
              "Mangal Pheras completed with final mantra",
            ],
            items: ["Mandap", "Sacred fire pit (havan kund)", "Ghee", "Samagri", "Puffed rice (laja)", "Bride's dupatta", "Groom's scarf"],
            familyRole: "Mahraj leads the mantras. Bride's brother feeds puffed rice into the fire during pheras. Parents witness from the mandap.",
          },
          {
            name: "Saptapadi",
            sanskrit: "Saptapadi",
            slug: "saptapadi",
            duration: "15 to 20 minutes",
            timing: "Immediately after or as part of the pheras",
            description: "The seven steps taken together by the couple, each step representing a vow for their married life. In some traditions this is performed separately from the pheras; in others, each step corresponds to a phera.",
            significance: "The Saptapadi is what legally and spiritually completes the marriage in Hindu law. After the seventh step, the marriage is considered irrevocable.",
            keySteps: [
              "Seven small mounds of rice or betel leaves placed in a line",
              "Couple walks to each mound together",
              "Step 1: Nourishment and sustenance",
              "Step 2: Strength and mutual support",
              "Step 3: Prosperity and shared wealth",
              "Step 4: Happiness and harmony",
              "Step 5: Strong and virtuous children",
              "Step 6: Good health and longevity",
              "Step 7: Lifelong friendship and loyalty",
            ],
            items: ["Seven small mounds of rice or betel leaves", "Decorative plate"],
            familyRole: "Mahraj recites the vow at each step. Couple walks together.",
          },
          {
            name: "Sindoor & Mangalsutra",
            slug: "sindoor-mangalsutra",
            duration: "10 minutes",
            timing: "After pheras / saptapadi",
            description: "The groom applies sindoor (vermilion) in the parting of the bride's hair and ties the mangalsutra (sacred necklace) around her neck. These are the primary symbols of a married Hindu woman.",
            significance: "Sindoor represents the wish for the husband's long life. The mangalsutra, made of black beads and gold, is believed to protect the marriage from evil. Together they mark the bride as married.",
            keySteps: [
              "Groom applies sindoor in bride's hair parting (maang)",
              "Mangalsutra tied around bride's neck with three knots",
              "Each knot represents commitment of mind, body, and soul",
              "Elders and guests bless the couple",
            ],
            items: ["Sindoor (vermilion powder)", "Mangalsutra necklace"],
            familyRole: "Groom performs both. Groom's sister may hand him the mangalsutra.",
          },
          {
            name: "Ashirvaad",
            slug: "ashirvaad",
            duration: "30 to 45 minutes",
            timing: "After the main ceremony",
            description: "Elders from both families bless the newlywed couple by placing their hands on the couple's heads, offering gifts, and sharing words of wisdom for married life.",
            significance: "Receiving blessings from elders is deeply valued in Hindu culture. Ashirvaad formally introduces the couple to the extended family as a married unit.",
            keySteps: [
              "Couple sits together and touches elders' feet",
              "Each elder blesses the couple",
              "Gifts and shagun presented to the couple",
              "Group photo with family",
            ],
            items: ["Gift envelopes", "Flower garlands"],
            familyRole: "All elders participate, starting with grandparents, then parents, then uncles and aunts.",
          },
        ],
      },
      {
        label: "Post-Wedding",
        ceremonies: [
          {
            name: "Vidaai",
            slug: "vidaai",
            duration: "20 to 30 minutes",
            timing: "End of the wedding, as bride departs",
            description: "The most emotional moment of a Hindu wedding. The bride says goodbye to her parents and childhood home, throwing handfuls of rice over her head as she leaves, wishing prosperity upon her birth family.",
            significance: "The rice thrown backward symbolizes the bride repaying her debt to her parents and wishing them continued abundance. It marks the transition from daughter to wife.",
            keySteps: [
              "Bride hugs and says goodbye to parents and siblings",
              "Bride throws handfuls of rice over her head backward",
              "Parents bid farewell with tears and blessings",
              "Groom's family welcomes her to the car",
              "Couple departs for groom's home",
            ],
            items: ["Rice", "Flower petals", "Decorated departure vehicle"],
            familyRole: "Bride's parents and siblings are central. Brothers may push the car as a sign of send-off.",
          },
          {
            name: "Griha Pravesh",
            sanskrit: "Griha Pravesh (Bridal)",
            slug: "griha-pravesh-bridal",
            duration: "30 to 45 minutes",
            timing: "When bride arrives at groom's home",
            description: "The bride's first entry into her new marital home. She is welcomed by her mother-in-law with an aarti and steps into the house by tipping a vessel of rice with her right foot, symbolizing that she brings abundance.",
            significance: "The rice vessel ritual signifies that the bride brings prosperity and good fortune into her new family. It is her formal initiation into the household.",
            keySteps: [
              "Mother-in-law performs aarti at the door",
              "Bride dips her feet in red liquid (alta) and steps on a white cloth",
              "Bride kicks a vessel of rice with her right foot at the threshold",
              "Rice grains scatter into the home (prosperity enters)",
              "Bride offered a glass of milk with a ring inside (playful game)",
            ],
            items: ["Aarti thali", "Alta (red dye)", "White cloth", "Vessel of rice", "Milk and ring"],
            familyRole: "Mother-in-law leads. Sisters-in-law participate in the ring-finding game.",
          },
          {
            name: "Pag Phera",
            slug: "pag-phera",
            duration: "Half-day visit",
            timing: "2 to 3 days after the wedding",
            description: "The bride returns to her parents' home for the first time after the wedding. Her parents welcome the couple, serve a meal, and send them back with gifts. It reassures the bride that she is always welcome.",
            significance: "Pag Phera eases the emotional transition for the bride by affirming that her parents' home is still her home. It strengthens the bond between the two families.",
            keySteps: [
              "Couple visits bride's parents' home",
              "Bride's family welcomes them with tilak and aarti",
              "Meal served (often the bride's favorite dishes)",
              "Gifts given to the couple",
              "Couple returns to groom's home",
            ],
            items: ["Gifts for the couple", "Home-cooked meal"],
            familyRole: "Bride's parents host. Groom is treated as a guest of honor.",
          },
          {
            name: "Griha Shanti",
            slug: "griha-shanti-wedding",
            duration: "1.5 to 2 hours",
            timing: "Within a week of the wedding",
            description: "A peace ceremony performed at the couple's new home to invoke harmony, health, and prosperity in their married life. A havan is performed and the home is blessed with Vedic mantras.",
            significance: "Griha Shanti removes any negative energies and blesses the home where the couple will build their life together. It is the spiritual housewarming of their married life.",
            keySteps: [
              "Havan (sacred fire) performed in the new home",
              "Navgraha mantras to harmonize planetary energies",
              "Prayers for peace, health, and prosperity",
              "Couple worships together as a new family unit",
              "Prasad distributed to neighbors and friends",
            ],
            items: ["Havan kund", "Havan samagri", "Ghee", "Navgraha items", "Flowers", "New clothes for the couple"],
            familyRole: "Couple performs the havan together. Parents may attend.",
          },
        ],
      },
    ],
  },

  // ───────────────────── BABY ─────────────────────
  {
    id: "baby",
    label: "New baby",
    icon: "baby",
    intro: "Hindu tradition marks a child's early life with a sequence of samskaras (sacred milestones) that bless their health, intellect, and future. Each ceremony is performed at a specific age or developmental stage.",
    subSections: [
      {
        label: "Birth & Early Days",
        ceremonies: [
          {
            name: "Jatakarma",
            sanskrit: "Jatakarma",
            slug: "jatakarma",
            duration: "30 minutes",
            timing: "Immediately after birth or within first few days",
            description: "The father welcomes the newborn into the world by whispering sacred mantras into the baby's ear, touching the baby's tongue with honey and ghee, and praying for the child's intelligence and longevity.",
            significance: "One of the first samskaras. It is believed that the mantras whispered at birth shape the child's spiritual foundation. Honey and ghee symbolize sweetness and nourishment in life.",
            keySteps: [
              "Father holds the baby and whispers Vedic mantras in the right ear",
              "Gold ring dipped in honey and ghee touched to baby's tongue",
              "Prayer for long life, intelligence, and good health",
              "Baby's birth details noted for horoscope preparation",
            ],
            items: ["Honey", "Ghee", "Gold ring or gold-dipped spoon", "Incense"],
            familyRole: "Father performs the rite. Mother rests and is honored.",
          },
          {
            name: "Chhathi",
            sanskrit: "Chhathi",
            slug: "chhathi",
            duration: "1 hour",
            timing: "6th day after birth",
            description: "On the sixth day, the mother and baby are ceremonially bathed, the birth room is cleaned, and the family gathers to celebrate. In many traditions, Chhathi Mata (the goddess of childbirth) is worshipped.",
            significance: "Marks the end of the initial seclusion period for mother and baby. The purification rituals acknowledge that the vulnerable first days are over and the baby is ready to be introduced to family.",
            keySteps: [
              "Ceremonial bath for mother and baby",
              "Birth room cleaned and purified",
              "Worship of Chhathi Mata",
              "Family gathers to see the baby",
              "Sweets distributed",
            ],
            items: ["New clothes for mother and baby", "Mustard oil", "Turmeric", "Sweets"],
            familyRole: "Maternal grandmother often leads. Women of the family participate.",
          },
          {
            name: "Namkaran",
            sanskrit: "Namkaran Sanskar",
            slug: "namkaran",
            duration: "1 to 1.5 hours",
            timing: "11th or 12th day after birth (or muhurat-based)",
            description: "The child receives their formal name through Vedic rites. The Mahraj may suggest auspicious letters based on the baby's birth chart (nakshatra). The name is whispered into the baby's ear and announced to the family.",
            significance: "In Hindu philosophy, a name shapes destiny. The Namkaran ceremony ensures the child's name is chosen with cosmic alignment and spiritual intention, not just personal preference.",
            keySteps: [
              "Ganesh pooja and havan performed",
              "Mahraj determines auspicious first letter from birth chart",
              "Parents choose the name beginning with that letter",
              "Father whispers the name into baby's right ear three times",
              "Name announced to the family",
              "Cradle ceremony: baby placed in a decorated cradle",
              "Elders bless the child",
            ],
            items: ["Cradle (decorated)", "New clothes for baby", "Honey", "Ghee", "Havan samagri", "Birth chart"],
            familyRole: "Father whispers the name. Maternal uncle may rock the cradle. Grandparents bless the child.",
          },
        ],
      },
      {
        label: "Growth Milestones",
        ceremonies: [
          {
            name: "Nishkraman",
            sanskrit: "Nishkraman",
            slug: "nishkraman",
            duration: "30 minutes",
            timing: "4th month after birth",
            description: "The baby's first outing from the home. The child is taken outside to see the sun and moon for the first time, symbolizing their introduction to the wider world.",
            significance: "Marks the child's transition from the protected home environment to the outside world. The sun represents the source of life and energy; showing the baby the sun invokes vitality.",
            keySteps: [
              "Brief pooja at home",
              "Baby dressed in new clothes",
              "Baby taken outside, shown the sun (or moon at night)",
              "Visit to a temple or sacred place",
              "Blessings from elders",
            ],
            items: ["New outfit for baby", "Flowers", "Tikka"],
            familyRole: "Father or maternal uncle carries the baby outside. Mother accompanies.",
          },
          {
            name: "Annaprashan",
            sanskrit: "Annaprashan",
            slug: "annaprashan",
            duration: "1 hour",
            timing: "6th month (boys) or 7th month (girls)",
            description: "The baby's first taste of solid food. Kheer (sweet rice pudding) is ceremonially fed to the child by the eldest family member, marking the transition from milk to grains.",
            significance: "Food is sacred in Hindu culture. Annaprashan ensures the child's first solid meal is blessed and offered with prayers for good health and nourishment throughout life.",
            keySteps: [
              "Baby dressed in new clothes and placed on parent's lap",
              "Brief pooja with Ganesh prayer",
              "Eldest member (usually grandfather) feeds baby the first bite of kheer",
              "Other foods may be placed in front of the baby to predict their interests",
              "Family shares the meal and celebrates",
            ],
            items: ["Silver bowl and spoon", "Kheer (rice pudding)", "Rice", "New clothes", "Payasam"],
            familyRole: "Grandfather or eldest family member feeds the first bite. Maternal uncle often gives the silver bowl.",
            modernNote: "The 'prediction game' (placing a book, money, clay, food before the baby to see what they grab first) is a popular addition.",
          },
          {
            name: "Mundan",
            sanskrit: "Mundan / Chudakarana",
            slug: "mundan",
            duration: "1 to 2 hours",
            timing: "1st, 3rd, or 5th year (odd years preferred)",
            description: "The child's first haircut. The head is shaved completely, and the hair is offered to a deity (often at a temple). It is believed to cleanse the child of any negativity from a past life.",
            significance: "Shaving the birth hair symbolizes purification and a fresh start. The act of offering the hair to God expresses gratitude for the child's life and good health.",
            keySteps: [
              "Pooja and havan before the shaving",
              "Barber shaves the child's head (or a symbolic first cut by the father)",
              "Haldi and sandalwood paste applied to the shaved head",
              "Hair collected and offered at a temple or immersed in holy water",
              "Child given new clothes",
              "Celebration and feast",
            ],
            items: ["New razor or scissors", "Haldi paste", "Sandalwood paste", "New clothes", "Coconut"],
            familyRole: "Father makes the first symbolic cut. Maternal uncle may hold the child. A barber completes the shaving.",
          },
          {
            name: "Karnavedha",
            sanskrit: "Karnavedha",
            slug: "karnavedha",
            duration: "30 to 45 minutes",
            timing: "6th or 7th month, or 3rd to 5th year",
            description: "The ceremonial piercing of the child's ears. Originally prescribed for both boys and girls in Vedic tradition, today it is most commonly performed for girls.",
            significance: "Ear piercing is one of the 16 samskaras. It is believed to enhance the child's hearing of sacred mantras and protect against certain diseases through acupressure points in the earlobes.",
            keySteps: [
              "Brief pooja and prayer for protection",
              "Right ear pierced first, then left",
              "Gold studs inserted",
              "Turmeric paste applied for healing",
              "Sweets distributed",
            ],
            items: ["Gold studs or earrings", "Turmeric", "Antiseptic", "Flowers"],
            familyRole: "Typically performed by a goldsmith or piercing professional. Father holds the child.",
          },
        ],
      },
    ],
  },

  // ───────────────────── HOME ─────────────────────
  {
    id: "home",
    label: "New home",
    icon: "home",
    intro: "A home is more than bricks and mortar in Hindu tradition. These ceremonies sanctify the space, align its energies, and invite divine protection and prosperity before a family moves in.",
    subSections: [
      {
        label: "Building & Moving In",
        ceremonies: [
          {
            name: "Bhoomi Pooja",
            sanskrit: "Bhoomi Pooja",
            slug: "bhoomi-pooja",
            duration: "1.5 to 2 hours",
            timing: "Before construction begins, muhurat-based",
            description: "The ground-breaking ceremony performed before construction begins on a new home or building. Mother Earth (Bhoomi Devi) is worshipped and asked for permission to build upon her.",
            significance: "Hindus revere the earth as a living entity. Bhoomi Pooja seeks forgiveness for disturbing the land and asks for blessings so the structure built upon it will be strong, safe, and prosperous.",
            keySteps: [
              "Site purified with water and turmeric",
              "Ganesh pooja at the northeast corner",
              "Worship of Bhoomi Devi and Vastu Purush",
              "Foundation stone placed with coins, grains, and kumkum",
              "Havan performed",
              "Coconut broken at the site",
              "First symbolic digging by the homeowner",
            ],
            items: ["Bricks", "Coins", "Grains (wheat, rice)", "Kumkum", "Coconut", "Havan samagri", "Foundation stone", "Mango leaves"],
            familyRole: "Homeowner makes the first dig. Spouse places the first brick. Mahraj performs the havan.",
          },
          {
            name: "Griha Pravesh",
            sanskrit: "Griha Pravesh",
            slug: "griha-pravesh",
            duration: "2.5 to 3 hours",
            timing: "Morning, muhurat-based (before noon preferred)",
            description: "The auspicious first entry into a new home. The family enters only after the Mahraj performs havan, Ganesh pooja, and Vastu prayers. The wife enters first, carrying a kalash (sacred pot), and boils milk in the new kitchen until it overflows, symbolizing abundance.",
            significance: "The home is the foundation of family life in Hindu culture. Griha Pravesh sanctifies the space, removes negative energies, and ensures the family enters with divine blessings and positive vibrations.",
            keySteps: [
              "Entrance decorated with mango leaves and rangoli",
              "Ganesh pooja performed at the entrance",
              "Havan (sacred fire) performed inside the home",
              "Kalash (sacred pot) placed at the entrance",
              "Wife carries the kalash and enters first with right foot",
              "Milk boiled on the stove until it overflows (signifying abundance)",
              "All rooms visited and blessed with incense",
              "Neighbors and guests served prasad",
            ],
            items: ["Kalash (brass pot)", "Coconut", "Mango leaves", "Havan kund and samagri", "Milk", "Rice", "Kumkum", "Rangoli powder", "Flowers", "Ghee lamp"],
            familyRole: "Wife enters first carrying the kalash. Husband follows. Children enter next. Mahraj leads all rituals.",
          },
          {
            name: "Vastu Shanti",
            sanskrit: "Vastu Shanti",
            slug: "vastu-shanti",
            duration: "2 to 3 hours",
            timing: "Before or after Griha Pravesh, or when moving into a pre-owned home",
            description: "A ceremony to harmonize the directional energies (Vastu) of the home. Each direction is governed by a deity; the ceremony ensures all are balanced and the home's energy is positive.",
            significance: "Vastu Shastra is the Hindu science of architecture and spatial arrangement. If a home has Vastu defects (wrong placement of kitchen, bedroom, entrance), Vastu Shanti can mitigate their effects through mantras and specific offerings.",
            keySteps: [
              "Vastu Purush pooja (deity who governs the home's energy grid)",
              "Offerings in all eight cardinal directions plus center",
              "Navgraha pooja to balance planetary influences",
              "Havan with Vastu-specific mantras",
              "Vastu yantra installed in the northeast of the home",
              "Each room blessed individually",
            ],
            items: ["Vastu yantra (metal plate)", "Grains in nine colors", "Colored powders for each direction", "Havan samagri", "Nine types of flowers", "Coconuts for each corner"],
            familyRole: "Both husband and wife participate in the havan. Mahraj guides the directional offerings.",
            modernNote: "Particularly popular when moving into a pre-owned home, a home that wasn't built with Vastu principles, or when things haven't been going well since moving in.",
          },
        ],
      },
    ],
  },

  // ───────────────────── BUSINESS ─────────────────────
  {
    id: "business",
    label: "New business",
    icon: "briefcase",
    intro: "Starting a new venture, opening a shop, or marking a business milestone, Hindu tradition offers ceremonies to remove obstacles, attract prosperity, and express gratitude for success.",
    subSections: [
      {
        label: "Launch & Prosperity",
        ceremonies: [
          {
            name: "Ganesh Pooja",
            sanskrit: "Ganesh Pooja",
            slug: "ganesh-pooja-business",
            duration: "1 to 1.5 hours",
            timing: "Before the business opens or on an auspicious day",
            description: "Lord Ganesh is worshipped as the remover of obstacles before starting any new venture. A murti or image is installed at the place of business and offered prayers, modak, and flowers.",
            significance: "Ganesh is always invoked first in Hindu tradition. For a business, his blessings are sought to clear the path of hurdles, ensure smooth operations, and bring wisdom in decision-making.",
            keySteps: [
              "Clean and prepare the pooja space at the business location",
              "Install Ganesh murti with turmeric and kumkum",
              "Chant Ganesh mantras (Om Gan Ganapataye Namah)",
              "Offer modak, laddoo, durva grass, and red flowers",
              "Perform aarti",
              "Break coconut and distribute prasad",
            ],
            items: ["Ganesh murti", "Turmeric", "Kumkum", "Durva grass", "Modak or laddoo", "Red flowers", "Coconut", "Incense", "Diya"],
            familyRole: "Business owner performs the pooja. Partners and key team members participate.",
          },
          {
            name: "Lakshmi Pooja",
            sanskrit: "Lakshmi Pooja",
            slug: "lakshmi-pooja-business",
            duration: "1 to 1.5 hours",
            timing: "Diwali, Dhanteras, or business opening day",
            description: "Goddess Lakshmi is worshipped for financial prosperity, abundance, and success. New account books may be opened and blessed. The business space is cleaned, decorated with diyas, and made fragrant.",
            significance: "Lakshmi follows where there is cleanliness, hard work, and devotion. This pooja invites her blessings into the workspace, ensuring financial stability and growth.",
            keySteps: [
              "Business premises thoroughly cleaned and decorated",
              "Lakshmi murti installed with gold coins and lotus flowers",
              "Chant Lakshmi mantras (Om Shreem Mahalakshmiyei Namaha)",
              "New account books or ledgers placed before the murti and blessed",
              "Coins and currency placed at the murti's feet",
              "Aarti performed and diyas lit throughout the space",
            ],
            items: ["Lakshmi murti or image", "Lotus flowers (or roses)", "Gold coins or token coins", "Diyas", "New account books or laptop", "Sweets"],
            familyRole: "Business owner and spouse perform together. Employees may participate in the aarti.",
            modernNote: "Many business owners place their laptop or first invoice at the altar for blessing alongside traditional account books.",
          },
          {
            name: "Satyanarayan Katha",
            sanskrit: "Satyanarayan Katha",
            slug: "satyanarayan-katha-business",
            duration: "1.5 to 2 hours",
            timing: "Full moon day (Purnima) or after a major business milestone",
            description: "A devotional storytelling ceremony honoring Lord Vishnu in his form as Satyanarayan. Five chapters are narrated, each illustrating the rewards of devotion and the consequences of neglecting one's vows.",
            significance: "Performed to express gratitude after success (a big deal, a new office, a profitable quarter) or to seek blessings before an important phase. The katha emphasizes truth, integrity, and keeping promises.",
            keySteps: [
              "Ganesh pooja to start",
              "Kalash sthapana (sacred pot installation)",
              "Five chapters of the katha narrated by the Mahraj",
              "Panchamrut offered to Lord Satyanarayan",
              "Sheera (sweet semolina) prepared as prasad",
              "Prasad distributed to all; none should refuse it (as per the katha's teaching)",
            ],
            items: ["Satyanarayan image or murti", "Kalash", "Panchamrut (milk, curd, honey, sugar, ghee)", "Banana leaves", "Fruits", "Tulsi", "Sheera ingredients (semolina, sugar, ghee)"],
            familyRole: "Business owner and family listen to the katha. All attendees receive prasad.",
          },
          {
            name: "Muhurat Pooja",
            sanskrit: "Muhurat Pooja",
            slug: "muhurat-pooja",
            duration: "45 minutes to 1 hour",
            timing: "At the exact auspicious time (muhurat) calculated by the Mahraj",
            description: "A time-specific blessing performed at the precise auspicious moment (muhurat) for launching a business, signing a deal, or starting operations. The Mahraj calculates the exact window based on planetary positions.",
            significance: "Timing is everything in Hindu tradition. A muhurat pooja ensures the venture begins at the most cosmically favorable moment, aligning with positive planetary energies.",
            keySteps: [
              "Mahraj calculates the exact muhurat (date and time window)",
              "Quick Ganesh prayer at the start of the muhurat",
              "Key business action performed during the window (first transaction, ribbon cutting, first email)",
              "Coconut broken to seal the auspicious start",
              "Sweets distributed to all present",
            ],
            items: ["Coconut", "Flowers", "Incense", "Kumkum", "Sweets"],
            familyRole: "Business owner performs the key action during the muhurat. Mahraj ensures timing is precise.",
            modernNote: "Popular for stock market opening trades (muhurat trading on Diwali), app launches, or signing important contracts.",
          },
        ],
      },
    ],
  },

  // ───────────────────── MILESTONES ─────────────────────
  {
    id: "milestone",
    label: "Milestones",
    icon: "star",
    intro: "Hindu tradition honors life's transitions with sacred ceremonies. From a child's first step into education to a grandparent's 60th birthday, each milestone is an opportunity to pause, pray, and celebrate.",
    subSections: [
      {
        label: "Education & Coming of Age",
        ceremonies: [
          {
            name: "Vidyarambha",
            sanskrit: "Vidyarambha / Aksharabhyasa",
            slug: "vidyarambha",
            duration: "1 hour",
            timing: "Age 3 to 5, on Vijayadashami or an auspicious day",
            description: "The child's formal introduction to learning. A Mahraj or the father guides the child's finger to write their first letter (often 'Om' or the first letter of the alphabet) on a plate of rice or sand.",
            significance: "Education is considered the highest pursuit in Hindu philosophy. Vidyarambha marks the moment a child begins their lifelong journey of knowledge, invoking Goddess Saraswati's blessings.",
            keySteps: [
              "Worship of Goddess Saraswati (deity of knowledge)",
              "Child sits on parent's lap",
              "Mahraj or father guides child's hand to write the first letter",
              "Letter written on a plate of rice or on a slate",
              "Child touches books and writing instruments as a blessing",
              "Prasad and sweets distributed",
            ],
            items: ["Plate of rice or sand", "Slate and chalk", "Books", "Saraswati image", "Flowers", "Incense"],
            familyRole: "Father or Mahraj guides the child's hand. Mother sits with the child.",
          },
          {
            name: "Upanayana",
            sanskrit: "Upanayana / Janeu / Thread Ceremony",
            slug: "upanayana",
            duration: "3 to 4 hours",
            timing: "Age 7 to 12, muhurat-based",
            description: "One of the most important samskaras. The boy receives the sacred thread (janeu) worn across the chest, symbolizing his spiritual rebirth. He is taught the Gayatri Mantra and enters the student phase of life (Brahmacharya).",
            significance: "The thread ceremony marks a 'second birth', transforming the child from a student of the world to a student of the scriptures. The three threads represent debt to teachers, parents, and God. After this, the boy may perform Sandhyavandana (daily prayers).",
            keySteps: [
              "Mundan (head shaving) as purification",
              "Sacred bath and wearing of new dhoti",
              "Havan performed",
              "Mahraj initiates the boy with the Gayatri Mantra (whispered in the ear)",
              "Sacred thread (janeu) placed across the left shoulder to right hip",
              "Boy takes a symbolic vow of studentship",
              "Boy begs for alms (bhiksha) from mother and relatives, signifying humility",
              "Boy is now considered 'twice-born' (dvija)",
            ],
            items: ["Sacred thread (janeu)", "New dhoti and angavastram", "Havan samagri", "Deer or kusha grass mat", "Danda (staff)", "Kamandalu (water pot)"],
            familyRole: "Father and Mahraj are central. Mother performs the symbolic first alms-giving. Maternal uncle often provides the clothes.",
          },
        ],
      },
      {
        label: "Celebrations & Gratitude",
        ceremonies: [
          {
            name: "Satyanarayan Katha",
            sanskrit: "Satyanarayan Katha",
            slug: "satyanarayan-katha-milestone",
            duration: "1.5 to 2 hours",
            timing: "Full moon day (Purnima), or after a milestone event",
            description: "Performed to mark graduations, promotions, new jobs, wedding anniversaries, and answered prayers. A devotional storytelling of Lord Vishnu's grace, followed by sharing of sheera prasad.",
            significance: "Satyanarayan Katha is the most commonly performed thanksgiving ceremony in Hindu households. It celebrates what you have received and reinforces the values of truth and gratitude.",
            keySteps: [
              "Ganesh pooja and Kalash sthapana",
              "Narration of the five chapters of the katha",
              "Offerings of panchamrut, fruits, and tulsi",
              "Sheera prepared and offered as prasad",
              "Everyone present listens and receives prasad (none should refuse)",
            ],
            items: ["Satyanarayan murti or image", "Kalash", "Panchamrut", "Fruits", "Tulsi", "Banana leaves", "Sheera ingredients"],
            familyRole: "The person being celebrated and their family sit through the katha. Neighbors and friends are invited.",
          },
          {
            name: "Ayush Homam",
            sanskrit: "Ayush Homam",
            slug: "ayush-homam",
            duration: "2 to 2.5 hours",
            timing: "Milestone birthdays (1st, 60th, 80th) or when health is a concern",
            description: "A Vedic fire ritual specifically invoking Ayur Devata (deity of longevity) for long life and good health. Herbal offerings are made into the fire while mantras from the Ayur Sukta are chanted.",
            significance: "Different from a general havan, Ayush Homam uses specific medicinal herbs and mantras targeting health and lifespan. It is especially significant for a child's first birthday and for elders' milestone birthdays.",
            keySteps: [
              "Ganesh pooja and Sankalp (statement of purpose)",
              "Sacred fire lit with specific woods (peepal, palash)",
              "108 offerings of herbal mixture into the fire",
              "Chanting of Ayur Sukta and Maha Mrityunjaya Mantra",
              "Abhishekam (ritual bathing) of the person being blessed",
              "New clothes worn after the ceremony",
              "Prasad and feast for attendees",
            ],
            items: ["Havan kund", "Specific herbal samagri (for Ayush)", "Ghee", "Specific woods", "New clothes", "Fruits"],
            familyRole: "The person being honored sits near the fire. Family makes offerings. Mahraj leads the chanting.",
          },
          {
            name: "Shashtipoorthi",
            sanskrit: "Shashtipoorthi",
            slug: "shashtipoorthi",
            duration: "3 to 4 hours",
            timing: "60th birthday",
            description: "A grand celebration of completing 60 years, also considered a second wedding. The couple renews their wedding vows by performing a condensed version of the Vivah ceremony, complete with new wedding attire.",
            significance: "60 years completes one full cycle of the Hindu calendar (5 cycles of 12 years). Shashtipoorthi celebrates surviving this full cycle and blesses the couple with continued health and togetherness for the next phase.",
            keySteps: [
              "Couple dresses in full wedding attire",
              "Havan performed",
              "Couple takes pheras (ceremonial rounds) around the fire again",
              "Renewed vows for the next phase of life",
              "Kanyadaan symbolically repeated (by a son or relative)",
              "Grand feast and celebration with family and friends",
            ],
            items: ["Wedding attire for the couple", "Havan kund and samagri", "Garlands", "Flowers", "Mandap (can be simpler than a wedding)"],
            familyRole: "Children and grandchildren organize the event. The couple is treated as bride and groom again.",
            modernNote: "Increasingly popular in the diaspora as a way to honor parents' milestone anniversary and give the family a reason to gather.",
          },
        ],
      },
    ],
  },

  // ───────────────────── REMEMBRANCE ─────────────────────
  {
    id: "remembrance",
    label: "Remembrance",
    icon: "flower",
    intro: "Hindu tradition honors those who have passed with specific rituals designed to guide the soul, express gratitude, and maintain the spiritual connection between the living and their ancestors.",
    subSections: [
      {
        label: "Funeral & Mourning",
        ceremonies: [
          {
            name: "Antyeshti",
            sanskrit: "Antyeshti / Antim Sanskar",
            slug: "antyeshti",
            duration: "Varies (cremation day)",
            timing: "As soon as possible after death, ideally same day or next morning",
            description: "The final samskara. The body is bathed, wrapped in white cloth, adorned with flowers, and cremated. The eldest son or closest male relative lights the funeral pyre. Mantras guide the soul on its journey.",
            significance: "Hindus believe the body is temporary and the soul (atman) is eternal. Cremation releases the soul from the physical body, allowing it to continue its spiritual journey. It is considered the most important duty a son performs for a parent.",
            keySteps: [
              "Body bathed and wrapped in white cloth",
              "Body placed on a bier and carried to the cremation ground",
              "Mantras chanted to guide the soul",
              "Eldest son or closest relative lights the pyre (or presses the button at an electric crematorium)",
              "Mourners circumambulate the pyre",
              "Kriya (last rites) performed by the Mahraj",
              "Asthi (ashes) collected on the 3rd day",
            ],
            items: ["White cloth", "Sandalwood", "Ghee", "Camphor", "Rice", "Flowers", "Sesame seeds (til)"],
            familyRole: "Eldest son is the primary performer. Close male relatives assist. Mahraj leads the prayers.",
          },
          {
            name: "Terahvin",
            sanskrit: "Terahvin / Tehravi",
            slug: "terahvin",
            duration: "2 to 3 hours",
            timing: "13th day after death",
            description: "Marks the end of the 13-day mourning period. A havan is performed, Brahmins are fed, and the family emerges from formal mourning. The house is cleaned, and normal activities resume.",
            significance: "Hindu tradition prescribes 13 days of mourning during which the family stays home, avoids celebrations, and focuses on prayer. Terahvin formally concludes this period and signals the family's re-entry into daily life.",
            keySteps: [
              "Home thoroughly cleaned and purified",
              "Havan performed",
              "Pind daan (rice ball offerings) for the departed soul",
              "Brahmins or Mahraj fed a meal",
              "Clothes and items donated in the name of the departed",
              "Family formally ends the mourning period",
              "Guests and relatives share a meal",
            ],
            items: ["Havan kund and samagri", "Rice for pind daan", "Til (sesame)", "Kusha grass", "New clothes for donation", "Food for Brahmin bhojan"],
            familyRole: "Eldest son performs the havan and pind daan. Entire family participates in the transition out of mourning.",
          },
        ],
      },
      {
        label: "Annual Remembrance",
        ceremonies: [
          {
            name: "Shraddh",
            sanskrit: "Shraddh",
            slug: "shraddh",
            duration: "1.5 to 2 hours",
            timing: "Annual tithi (death anniversary) or during Pitru Paksha",
            description: "An annual ceremony to honor departed ancestors. Food offerings (pind) are made, mantras are chanted, and Brahmins are fed in the name of the departed. Shraddh is performed every year on the lunar date of the person's passing.",
            significance: "Hindus believe that the living have a duty to nourish and honor their ancestors. Shraddh ensures the departed soul receives spiritual sustenance and continues its peaceful journey in the afterlife.",
            keySteps: [
              "Family observes a day of prayer and remembrance",
              "Havan performed with specific mantras for the departed",
              "Pind daan: rice balls offered with sesame and water",
              "Tarpan: water offering to ancestors",
              "Brahmins fed a full meal in the departed's name",
              "Donations made (clothes, food, money) in the departed's name",
              "Family shares a simple vegetarian meal",
            ],
            items: ["Til (sesame seeds)", "Kusha grass", "Rice for pind", "Barley", "Water for tarpan", "Darbha grass", "Food for Brahmin bhojan"],
            familyRole: "Eldest son or closest male relative performs the rites. All family members participate in the prayers and meal.",
          },
          {
            name: "Tarpan",
            sanskrit: "Tarpan / Tarpana",
            slug: "tarpan",
            duration: "30 to 45 minutes",
            timing: "During Pitru Paksha (September/October), Amavasya (new moon), or eclipses",
            description: "A water-based offering to ancestors. Standing in water or at the riverside, the person pours water mixed with sesame seeds and barley through their cupped hands while reciting the names of departed ancestors.",
            significance: "Tarpan literally means 'to satisfy'. The offering of water satisfies the thirst of ancestral souls and maintains the spiritual bond between generations. It is simpler than a full Shraddh and can be done more frequently.",
            keySteps: [
              "Person faces south (the direction of Yama, lord of death)",
              "Hands cupped with water, sesame, and barley",
              "Water poured while reciting ancestor's name and gotra (lineage)",
              "Three offerings made: to gods (devas), to sages (rishis), to ancestors (pitrs)",
              "Prayer for ancestors' peace and liberation",
            ],
            items: ["Water", "Sesame seeds (til)", "Barley", "Kusha grass ring (worn on finger)"],
            familyRole: "Typically performed by the eldest son or any male descendant. Women may also perform it in the absence of male heirs.",
            modernNote: "Can be performed at home using a small vessel if visiting a river is not possible.",
          },
          {
            name: "Pind Daan",
            sanskrit: "Pind Daan",
            slug: "pind-daan",
            duration: "1 to 2 hours",
            timing: "Pitru Paksha, or at holy sites like Gaya, Varanasi, Prayagraj",
            description: "Ritual offerings of rice balls (pind) made at sacred sites to liberate the souls of ancestors. Gaya in Bihar is considered the holiest site for Pind Daan; performing it there is believed to grant moksha (liberation) to ancestors.",
            significance: "Pind Daan is believed to directly nourish the departed soul and help it progress in the afterlife. The rice ball represents the body; offering it symbolizes giving form and sustenance to the formless soul.",
            keySteps: [
              "Travel to a sacred site (Gaya, Varanasi, or Prayagraj preferred)",
              "Ritual bath in holy water",
              "Rice balls prepared with sesame, barley, honey, and ghee",
              "Pind placed on kusha grass while mantras are chanted",
              "Offerings made at specific sacred spots (vedi)",
              "Tarpan (water offering) performed alongside",
              "Mahraj or local priest confirms the rites",
            ],
            items: ["Rice", "Sesame seeds", "Barley", "Honey", "Ghee", "Kusha grass", "Water"],
            familyRole: "Eldest son or heir performs the rite. A local Mahraj or Pandas (hereditary priests at pilgrimage sites) guide the process.",
            modernNote: "For those unable to visit Gaya, a Mahraj can perform a simplified version at home or at a local temple.",
          },
        ],
      },
    ],
  },
];
